language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
sudo: false
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache: cargo
before_cache:
- cargo prune
before_script:
- cargo install cargo-prune
